AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template in which is created lambda layer issuing helm, kubectl and aws-cli binaries.

Parameters:
  LambdaLayerName:
    Type: String
    Default: etp-k8s-eks-kubectl-layer

Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LambdaLayerName
      ContentUri: ./lambda-layer.zip
      CompatibleRuntimes: 
        - provided
      RetentionPolicy: Retain

Outputs:
  LambdaLayerARN:
    Description: Amazon Resource Name of Lambda Layer provisioned.
    Value: !Ref LambdaLayer
    Export:
      Name: !Sub 'LambdaLayerARN-${AWS::StackName}'